import Head from "next/head";
import { LinkComponent } from "../components";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LinkComponent Route={"places"}>الاماكن</LinkComponent>
      <LinkComponent Route={"tours"}>الخطط السياحية</LinkComponent>
      <LinkComponent Route={"events"}>الاحداث</LinkComponent>
      <LinkComponent Route={"artCulture"}>ثقافة وفن</LinkComponent>
    </>
  );
}
